name: Build the .pdf document from LaTeX file
on: [push]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
      - name: rename the .pdf file
        run: mv main.pdf cv.pdf
      - name: Add the pdf to Github Release
        uses: svenstaro/upload-release-action@2.6.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: cv.pdf
          asset_name: cv
          tag: ${{ github.ref }}
          overwrite: true
          body: "This is my release text"

