name: Build the .pdf document from LaTeX file
on: 
  push:
    branches:
      - main

jobs:
  build_latex:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
      - name: rename the .pdf file
        run: mv main.pdf cv.pdf
      - name: Convert to Word Docx format
        uses: docker://pandoc/core:3.1.1
        with:
          args: -s main.tex --bibliography ./bib/bibliography.bib --csl=ieee.csl --citeproc -o cv.docx
      - name: Add the pdf to Github Release
        uses: svenstaro/upload-release-action@2.6.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: cv.pdf
          asset_name: cv.pdf
          tag: UpdatedCV
          overwrite: true
          body: "PDF version of my CV"
      - name: Add the .docx to Github Release
        uses: svenstaro/upload-release-action@2.6.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: cv.docx
          asset_name: cv.docx
          tag: UpdatedCV
          overwrite: true
          body: "Word version of my CV"

